.TH "/home/rectoria/projects/epitech/CPP/cpp_arcade/interfaces Directory Reference" 3 "Thu Apr 12 2018" "cpp_arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/rectoria/projects/epitech/CPP/cpp_arcade/interfaces Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBIGameLib\&.hpp\fP"
.br
.RI "Game libraries dedicated class interface\&. "
.ti -1c
.RI "file \fBIGraphicLib\&.hpp\fP"
.br
.RI "Graphic libraries dedicated class interface\&. "
.in -1c
