.TH "/home/rectoria/projects/epitech/CPP/cpp_arcade Directory Reference" 3 "Thu Apr 12 2018" "cpp_arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/rectoria/projects/epitech/CPP/cpp_arcade Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcmake\-build\-debug\fP"
.br
.ti -1c
.RI "directory \fBgames\fP"
.br
.ti -1c
.RI "directory \fBlib\fP"
.br
.in -1c
