.TH "/home/rectoria/projects/epitech/CPP/cpp_arcade/include Directory Reference" 3 "Thu Apr 12 2018" "cpp_arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/rectoria/projects/epitech/CPP/cpp_arcade/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBColor\&.hpp\fP"
.br
.RI "Color class, pixel-like\&. "
.ti -1c
.RI "file \fBKeys\&.hpp\fP"
.br
.RI "Keys enum\&. "
.ti -1c
.RI "file \fBPixelBox\&.hpp\fP"
.br
.RI "PixelBox class, similar to a rectangle of pixels\&. "
.ti -1c
.RI "file \fBTextBox\&.hpp\fP"
.br
.RI "TextBox class, similar to a text rectangle\&. "
.ti -1c
.RI "file \fBVect\&.hpp\fP"
.br
.RI "Project-specific vector template\&. "
.in -1c
