.TH "Arcade::Score" 3 "Thu Apr 12 2018" "cpp_arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::Score
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddGame\fP (std::string &)"
.br
.ti -1c
.RI "std::map< std::string, std::string > \fBgetGameStats\fP (std::string &)"
.br
.ti -1c
.RI "int \fBgetPlayerScore\fP (std::string &, std::string &)"
.br
.ti -1c
.RI "void \fBwriteStats\fP (std::string)"
.br
.ti -1c
.RI "void \fBsetScore\fP (std::string &, std::string &, unsigned)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_arcade from the source code\&.
