.TH "Arcade::Menu" 3 "Thu Apr 12 2018" "cpp_arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::Menu
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetLists\fP (std::vector< \fBDLLoader\fP< \fBIGameLib\fP > *> *, std::vector< \fBDLLoader\fP< \fBIGraphicLib\fP > *> *)"
.br
.ti -1c
.RI "void \fBrefresh\fP (\fBIGraphicLib\fP *, unsigned, \fBArcade::Score\fP)"
.br
.ti -1c
.RI "unsigned \fBapplyEvent\fP (\fBKeys\fP)"
.br
.ti -1c
.RI "std::string \fBgetUserName\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_arcade from the source code\&.
