.TH "Arcade" 3 "Thu Apr 12 2018" "cpp_arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade \- \fBArcade\fP project namespace\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColor\fP"
.br
.RI "\fBColor\fP class\&. "
.ti -1c
.RI "class \fBCore\fP"
.br
.ti -1c
.RI "class \fBIGameLib\fP"
.br
.RI "Game libraries virtual class\&. "
.ti -1c
.RI "class \fBIGraphicLib\fP"
.br
.RI "Graphic libraries virtual class\&. "
.ti -1c
.RI "class \fBMenu\fP"
.br
.ti -1c
.RI "class \fBNCurses\fP"
.br
.ti -1c
.RI "class \fBNibbler\fP"
.br
.ti -1c
.RI "class \fBPacman\fP"
.br
.ti -1c
.RI "class \fBPixelBox\fP"
.br
.RI "\fBPixelBox\fP class\&. "
.ti -1c
.RI "class \fBScore\fP"
.br
.ti -1c
.RI "class \fBSdl2\fP"
.br
.ti -1c
.RI "class \fBSfml\fP"
.br
.ti -1c
.RI "class \fBTextBox\fP"
.br
.RI "\fBTextBox\fP class\&. "
.ti -1c
.RI "class \fBVect\fP"
.br
.RI "\fBVect\fP class template\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBKeys\fP { \fBNONE\fP, \fBA\fP, \fBB\fP, \fBC\fP, \fBD\fP, \fBE\fP, \fBF\fP, \fBG\fP, \fBH\fP, \fBI\fP, \fBJ\fP, \fBK\fP, \fBL\fP, \fBM\fP, \fBN\fP, \fBO\fP, \fBP\fP, \fBQ\fP, \fBR\fP, \fBS\fP, \fBT\fP, \fBU\fP, \fBV\fP, \fBW\fP, \fBX\fP, \fBY\fP, \fBZ\fP, \fBLEFT\fP, \fBRIGHT\fP, \fBUP\fP, \fBDOWN\fP, \fBENTER\fP, \fBSPACE\fP, \fBDELETE\fP, \fBBACKSPACE\fP, \fBTAB\fP, \fBESC\fP, \fBMOUSELEFT\fP, \fBMOUSERIGHT\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBArcade\fP project namespace\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBArcade::Keys\fP"
All those keys should be handled by any graphic libraries or any games 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_arcade from the source code\&.
