.TH "Arcade::Core" 3 "Thu Apr 12 2018" "cpp_arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::Core
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCore\fP (std::string)"
.br
.ti -1c
.RI "bool \fBstart\fP ()"
.br
.ti -1c
.RI "size_t \fBgetLibIdx\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_arcade from the source code\&.
