.TH "/home/rectoria/projects/epitech/CPP/cpp_arcade/include/Color.hpp" 3 "Thu Apr 12 2018" "cpp_arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/rectoria/projects/epitech/CPP/cpp_arcade/include/Color.hpp \- Color class, pixel-like\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArcade::Color\fP"
.br
.RI "\fBColor\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBArcade\fP"
.br
.RI "\fBArcade\fP project namespace\&. "
.in -1c
.SH "Detailed Description"
.PP 
Color class, pixel-like\&. 


.PP
\fBAuthors:\fP
.RS 4
https://github.com/EPITECH-Strasbourg-2021/CPP-Arcade-Spec
.RE
.PP
Class used by games and graphic libraries, as a color's array All functions must be implemented correctly for libraries to function properly\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_arcade from the source code\&.
