.TH "/home/rectoria/projects/epitech/CPP/cpp_arcade/interfaces/IGraphicLib.hpp" 3 "Thu Apr 12 2018" "cpp_arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/rectoria/projects/epitech/CPP/cpp_arcade/interfaces/IGraphicLib.hpp \- Graphic libraries dedicated class interface\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'Vect\&.hpp'\fP
.br
\fC#include 'PixelBox\&.hpp'\fP
.br
\fC#include 'TextBox\&.hpp'\fP
.br
\fC#include 'Keys\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArcade::IGraphicLib\fP"
.br
.RI "Graphic libraries virtual class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBArcade\fP"
.br
.RI "\fBArcade\fP project namespace\&. "
.in -1c
.SH "Detailed Description"
.PP 
Graphic libraries dedicated class interface\&. 


.PP
\fBAuthors:\fP
.RS 4
https://github.com/EPITECH-Strasbourg-2021/CPP-Arcade-Spec
.RE
.PP
Interface used by graphic libraries All functions must be implemented correctly for the kernel to handle the graphic libraries\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_arcade from the source code\&.
