.TH "/home/rectoria/projects/epitech/CPP/cpp_arcade/include/Keys.hpp" 3 "Thu Apr 12 2018" "cpp_arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/rectoria/projects/epitech/CPP/cpp_arcade/include/Keys.hpp \- Keys enum\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBArcade\fP"
.br
.RI "\fBArcade\fP project namespace\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBArcade::Keys\fP { \fBNONE\fP, \fBA\fP, \fBB\fP, \fBC\fP, \fBD\fP, \fBE\fP, \fBF\fP, \fBG\fP, \fBH\fP, \fBI\fP, \fBJ\fP, \fBK\fP, \fBL\fP, \fBM\fP, \fBN\fP, \fBO\fP, \fBP\fP, \fBQ\fP, \fBR\fP, \fBS\fP, \fBT\fP, \fBU\fP, \fBV\fP, \fBW\fP, \fBX\fP, \fBY\fP, \fBZ\fP, \fBLEFT\fP, \fBRIGHT\fP, \fBUP\fP, \fBDOWN\fP, \fBENTER\fP, \fBSPACE\fP, \fBDELETE\fP, \fBBACKSPACE\fP, \fBTAB\fP, \fBESC\fP, \fBMOUSELEFT\fP, \fBMOUSERIGHT\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Keys enum\&. 


.PP
\fBAuthors:\fP
.RS 4
https://github.com/EPITECH-Strasbourg-2021/CPP-Arcade-Spec
.RE
.PP
Key Enum, each graphics library must store a map in order to convert the specific library key code into one of this enum code so that it can be used by other components independently of the graphics library\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_arcade from the source code\&.
