.TH "/home/rectoria/projects/epitech/CPP/cpp_arcade/include/Vect.hpp" 3 "Thu Apr 12 2018" "cpp_arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/rectoria/projects/epitech/CPP/cpp_arcade/include/Vect.hpp \- Project-specific vector template\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArcade::Vect< T >\fP"
.br
.RI "\fBVect\fP class template\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBArcade\fP"
.br
.RI "\fBArcade\fP project namespace\&. "
.in -1c
.SH "Detailed Description"
.PP 
Project-specific vector template\&. 


.PP
\fBAuthors:\fP
.RS 4
https://github.com/EPITECH-Strasbourg-2021/CPP-Arcade-Spec
.RE
.PP
Template used to store and perform arithmetic operations on coordinates\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_arcade from the source code\&.
